# Generated by Django 5.2.4 on 2025-07-16 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registered_users',
            field=models.ManyToManyField(related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
