version: "3.9"

services:
  frontend:
    build:
      context: ./newfrontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./newfrontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
