# Generated by Django 5.2.4 on 2025-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemTitle', models.CharField(max_length=30)),
                ('problemStatement', models.TextField()),
                ('totalAccepted', models.IntegerField(default=0)),
                ('totalRejected', models.IntegerField(default=0)),
                ('sample_testcase_INP', models.TextField(default='')),
                ('sample_testcase_OUT', models.TextField(default='no constraints provided')),
                ('constraints', models.TextField(default='')),
                ('difficultyLevel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('difficultyLevel', models.CharField(max_length=30)),
                ('problemSetTitle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to='')),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=10)),
                ('success', models.BooleanField(default=False)),
                ('runtime', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='testcases/inputs/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='testcases/outputs/')),
            ],
        ),
    ]
