# Generated by Django 5.2.4 on 2025-07-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memoryLimit',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='problem',
            name='timeLimit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='problem',
            name='topics',
            field=models.CharField(default=''),
        ),
    ]
