# Generated by Django 5.2.4 on 2025-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_problem_memorylimit_problem_timelimit_problem_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topics',
            field=models.TextField(default=''),
        ),
    ]
