# Generated by Django 5.2.3 on 2025-07-07 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_runcode_solution_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='runcode',
            name='ran_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 13, 10, 52, 474002, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='runcode',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
