# Generated by Django 5.2.4 on 2025-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_alter_problem_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='topics',
            field=models.TextField(default=''),
        ),
    ]
