# Generated by Django 5.2.3 on 2025-07-07 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_runcode_ran_at_alter_runcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='solutionCode',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='runcode',
            name='ran_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 13, 15, 51, 727507, tzinfo=datetime.timezone.utc)),
        ),
    ]
