# Generated by Django 5.2.3 on 2025-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_rename_solutioncode_solution_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runcode',
            name='language',
            field=models.CharField(default='py', max_length=10),
        ),
        migrations.AlterField(
            model_name='runcode',
            name='ran_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
