# Generated by Django 5.2.4 on 2025-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_problemset_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(),
        ),
    ]
