# Generated by Django 5.2.4 on 2025-07-09 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_runcode_language_alter_runcode_ran_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='inputFile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outputFile',
            field=models.TextField(),
        ),
    ]
