# Generated by Django 5.2.4 on 2025-07-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_alter_solution_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestCodeForProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
                ('language', models.CharField(default='cpp')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latestCode', to='problem.problem')),
            ],
        ),
    ]
