# Generated by Django 5.2.4 on 2025-07-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_remove_problem_author_name_alter_problem_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunCode',
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_testcase_INP',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_testcase_OUT',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='inputFile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outputFile',
            field=models.FileField(upload_to=''),
        ),
    ]
