# Generated by Django 5.2.4 on 2025-07-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_delete_runcode_problem_sample_testcase_inp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(default=''),
        ),
    ]
