# Generated by Django 5.2.4 on 2025-07-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_problem_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_testcase_OUT',
            field=models.TextField(default='no constraints provided'),
        ),
    ]
