# Generated by Django 5.2.4 on 2025-07-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_alter_problem_sample_testcase_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='inputFile',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='outputFile',
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='testcases/inputs/'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='testcases/outputs/'),
        ),
    ]
